// =========================================================================
// BASE DE DATOS DE INVITADOS INDEPENDIENTE (invitados.js)
// =========================================================================

const baseInvitadosEstricta = {
    // Invitados novio INICIO
    "sanchez espinosa": { integrantes: ["Donaldo", "Martha"], confirmado: false },
    "sanchez aguilera": { integrantes: ["Illi", "Jooy", "Julián [niño]", "José", "Irma"], confirmado: false },
    "sanchez miranda": { integrantes: ["Jesús", "Griselda", "Cristopher", "Desari [niño]", "Lucian [niño]"], confirmado: false },
    "sanchez castillo": { integrantes: ["Armando", "Doan [niño]", "Kareem [niño]"], confirmado: false },
    "sanchez hernandez": { integrantes: ["Nestor", "Elizabeth", "Hannia [niño]", "Alice [niño]"], confirmado: false },
    "sanchez leon": { integrantes: ["Niels", "Silvia", "Melanie [niño]", "Lilith [niño]", "Elena"], confirmado: false },
    "sanabria betancourt": { integrantes: ["Erik"], confirmado: false },
    "rosas galicia": { integrantes: ["David", "Asela", "Roberthor"], confirmado: false },
    "rosas juarez": { integrantes: ["Fernando", "Brenda", "Tania Fernanda"], confirmado: false },
    "escobar aguilera": { integrantes: ["Carlos", "Irma", "Carla", "Martines A. Sharim"], confirmado: false },
    "garcia espinosa": { integrantes: ["Ángel", "Eugenia", "Hayde"], confirmado: false },
    "piña garcia": { integrantes: ["Zayra", "Armando Alberto", "Leonardo", "Tadeo", "Guadalupe", "Angeles"], confirmado: false },
    "garcia alfaro": { integrantes: ["Roman", "Elvira", "Ángel", "Logan", "Matias", "Romina"], confirmado: false },
    "calixto garcia": { integrantes: ["Natalia", "Pedro"], confirmado: false },
    "sanchez jaramillo": { integrantes: ["J. Consepcion", "Elena", "Brandon", "Brenda"], confirmado: false },
    "sanchez rodriguez": { integrantes: ["Hugo", "Marce", "Sofía [niño]"], confirmado: false },
    "guerrero sanchez": { integrantes: ["Hayde", "Jorge", "Emilio [niño]", "Valentina [niño]"], confirmado: false },
    "salas sanchez": { integrantes: ["Marisol", "Andres", "Camila Monserrat [niño]", "Liam Santiago [niño]"], confirmado: false },
    "baez anastasio": { integrantes: ["José Eduardo", "+1 pase"], confirmado: false },
    "montiel matilde": { integrantes: ["Donaldo", "Victoria", " Lyan [niño]"], confirmado: false },
<<<<<<< HEAD
    "romero velazquez": { integrantes: ["Alejandro", "+1 pase"], confirmado: false },//74 pases sin confirmar
    // Invitados novia INICIO
    "espinoza salvador": { integrantes: ["Edgardo", "Elvia", "Joan"], confirmado: false },
    "meza salvador": { integrantes: ["Adelina", "Juan Carlos", "Ariana", "Ximena", "Isaac"], confirmado: false },
    "salvador remigio": { integrantes: ["Roberto", "Griselda", "Renata", "Isai", "Carla", "Adelina", "Roberto"], confirmado: false },
    "maldonado salvador": { integrantes: ["Rocio", "Angeles", "Rocio h.", "Norberto", "Josue", "Carlos"], confirmado: false },
    "espinoza martinez": { integrantes: ["Margarita", "Ricardo"], confirmado: false },
    "espinoza cardoso": { integrantes: ["Ángel", "Paula", "Alison", "Santiago [niño]"], confirmado: false },
    "mendoza espinoza": { integrantes: ["Arelí", "Samantha", "Johan", "Andrik"], confirmado: false },
    "jaramillo espinoza": { integrantes: ["Víctor", "Verónica", "Cristian", "Estefania", "Sebastián [niño]"], confirmado: false },
    "salvador beristain": { integrantes: ["Omar", "Alejandra", "Mariana", "Omar h."], confirmado: false },
    "salvador gonzalez": { integrantes: ["Rubén", "Marcos"], confirmado: false },
    "salvador eulogio": { integrantes: ["Jesús", "Carolina", "Jazmín", "Samuel", "Monserrat"], confirmado: false },
    "corpus carrazco": { integrantes: ["César", "Luz"], confirmado: false },
    "guzman gaspar": { integrantes: ["Giovani", "Nayeli"], confirmado: false },
    "garcia gallaga": { integrantes: ["Enrique", "Silvia"], confirmado: false },
    "oropeza herrera": { integrantes: ["José Alfredo", "+1 pase"], confirmado: false },
    "perez sanchez": { integrantes: ["Fernando"], confirmado: false },
    "lopez morales": { integrantes: ["Enrique"], confirmado: false },
    "quiroz martinez": { integrantes: ["Misael"], confirmado: false },
    "garcia diaz": { integrantes: ["Elizabeth Ketzalzin", "+1 pase"], confirmado: false },
    "torres benavides": { integrantes: ["Alberto", "Marisela", "Angelica", "+1 pase", "Diego", "+1 pase","+1 pase"], confirmado: false },
    "ledezma ": { integrantes: ["Liliana"], confirmado: false },
    "velazquez soriano": { integrantes: ["Zelzin"], confirmado: false },
    "venta martinez": { integrantes: ["Mitzi"], confirmado: false },
    "rivera cortes": { integrantes: ["Alexis"], confirmado: false }
    // Inivitados novia FIN
};

const nombresVisualesFamilias = {
    // Invitados novio INICIO
    "sanchez espinosa": "Sánchez Espinosa",
    "sanchez aguilera": "Sánchez Aguilera",
    "sanchez miranda": "Sánchez Miranda",
    "sanchez castillo": "Sánchez Castillo",
    "sanchez hernandez": "Sánchez Hernández",
    "sanchez leon": "Sánchez León",
    "sanabria betancourt": "Sanabria Betancourt",
    "rosas galicia": "Rosas Galicia",
    "rosas juarez": "Rosas Juárez",
    "escobar aguilera": "Escobar Aguilera",
    "garcia espinosa": "García Espinosa",
    "piña garcia": "Piña García",
    "garcia alfaro": "García Alfaro",
    "calixto garcia": "Calixto García",
    "sanchez jaramillo": "Sánchez Jaramillo",
    "sanchez rodriguez": "Sánchez Rodríguez",
    "guerrero sanchez": "Guerrero Sánchez",
    "salas sanchez": "Salas Sánchez",
    "baez anastacio": "Báez Anastacio",
    "montiel matilde": "Montiel Matilde",
    "romero velazquez": "Romero Velázquez",
    // Invitados novia INICIO
    "espinoza salvador": "Espinoza Salvador",
    "meza salvador": "Meza Salvador",
    "salvador remigio": "Salvador Remigio",
    "salvador lopez": "Salvador López",
    "maldonado salvador": "Maldonado Salvador",
    "espinoza martinez": "Espinoza Martínez",
    "espinoza cardoso": "Espinoza Cardoso",
    "mendoza espinoza": "Mendoza Espinoza",
    "jaramillo espinoza": "Jaramillo Espinoza",
    "salvador beristain": "Salvador Beristain",
    "salvador gonzalez": "Salvador González",
    "salvador eulogio": "Salvador Eulogio",
    "corpus carrazco": "Corpus Carrazco",
    "guzman gaspar": "Gúzman Gaspar",
    "garcia gallaga": "García Gallaga",
    "oropeza herrera": "Oropeza Herrera",
    "perez sanchez": "Pérez Sánchez",
    "lopez morales": "López Morales",
    "quiroz martinez": "Quiroz Martínez",
    "garcia diaz": "García Díaz",
    "torres benavides": "Torrez Benavides",
    "ledezma ": "Ledezma",
    "velazquez soriano": "Velázquez Soriano",
    "venta martinez": "Venta Martínez",
    "rivera cortes": "Rivera Córtes"
    // Inivitados novia FIN
};