// =========================================================================
// BASE DE DATOS DE INVITADOS INDEPENDIENTE (invitados.js)
// =========================================================================

const baseInvitadosEstricta = {
    // Invitados novio INICIO
    "sanchez espinoza": { integrantes: ["Andrew", "Atzareel", "Control de invitaciones"], confirmado: false },
    "sanchez espinosa": { integrantes: ["Donaldo", "Martha"], confirmado: false },
    "sanchez aguilera": { integrantes: ["Illi", "Jooy", "Julián [niño]", "José", "Irma"], confirmado: false },
    "sanchez miranda": { integrantes: ["Jesús", "Griselda", "Cristopher", "Desari [niño]", "Lucian [niño]"], confirmado: false },
    "sanchez castillo": { integrantes: ["Armando", "Doan [niño]", "Kareem [niño]"], confirmado: false },
    "sanchez hernandez": { integrantes: ["Nestor", "Elizabeth", "Hannia [niño]", "Alice [niño]"], confirmado: false },
    "sanchez leon": { integrantes: ["Niels", "Silvia", "Melanie [niño]", "Lilith [niño]", "Elena"], confirmado: false },
    "sanabria betancourt": { integrantes: ["Erik"], confirmado: false },
    "rosas galicia": { integrantes: ["David", "Asela", "Roberthor"], confirmado: false },
    "rosas juarez": { integrantes: ["Fernando", "Brenda", "Tania Fernanda"], confirmado: false },
    "escobar aguilera": { integrantes: ["Carlos", "Irma", "Carla", "Martines A. Sharim"], confirmado: false },
    "garcia espinosa": { integrantes: ["Ángel", "Eugenia", "Hayde"], confirmado: false },
    "piña garcia": { integrantes: ["Zayra", "Armando Alberto", "Leonardo", "Tadeo [bb]", "Guadalupe", "Angeles"], confirmado: false },
    "garcia alfaro": { integrantes: ["Roman", "Elvira", "Ángel", "Logan", "Matias", "Romina"], confirmado: false },
    "calixto garcia": { integrantes: ["Natalia", "Pedro"], confirmado: false },
    "sanchez jaramillo": { integrantes: ["J. Consepcion", "Elena", "Brandon", "Brenda"], confirmado: false },
    "sanchez rodriguez": { integrantes: ["Hugo", "Marce", "Sofía [niño]"], confirmado: false },
    "guerrero sanchez": { integrantes: ["Hayde", "Jorge", "Emilio [niño]", "Valentina [niño]"], confirmado: false },
    "salas sanchez": { integrantes: ["Marisol", "Andres", "Camila Monserrat [niño]", "Liam Santiago [niño]"], confirmado: false },
    "baez anastasio": { integrantes: ["José Eduardo", "+1 pase"], confirmado: false },
    "montiel matilde": { integrantes: ["Donaldo", "Victoria", " Lyan [niño]"], confirmado: false },
    "romero velazquez": { integrantes: ["Alejandro", "+1 pase"], confirmado: false },
    "mendez olguin": { integrantes: ["N. Angélica", "+1 pase"], confirmado: false },
    "herrera sanchez": { integrantes: ["Hansel", "Cassandra"], confirmado: false },
    "curiel gomez": { integrantes: ["Iván", "+1 pase", "+1 pase"], confirmado: false },
    "vazquez cano": { integrantes: ["Gustavo", "+1 pase"], confirmado: false },
    "zarate mejia": { integrantes: ["Abraham", "+1 pase"], confirmado: false },
    "silva gonzalez": { integrantes: ["Alejandro", "+1 pase"], confirmado: false },
    "garcia carreon": { integrantes: ["Luis", "Valentina"], confirmado: false },
    "perez nieto": { integrantes: ["Paulina", "Michael", "Roman [niño]"], confirmado: false },
    "cabrera bolaños": { integrantes: ["Sergio", "Elizabeth"], confirmado: false },
    //"espinosa torres": { integrantes: ["Germán", "Lorena", "", ""], confirmado: false },
    // Invitados novia INICIO
    "espinoza salvador": { integrantes: ["Edgardo", "Elvia", "Joan"], confirmado: false },
    "meza salvador": { integrantes: ["Adelina", "Juan Carlos", "Ariana", "Ximena", "Isaac", "Emilio [bb]"], confirmado: false },
    "salvador remigio": { integrantes: ["Roberto", "Griselda", "Renata", "Isai", "Carla", "Adelina", "Roberto"], confirmado: false },
    "maldonado salvador": { integrantes: ["Rocio", "Angeles", "Rocio h.", "Norberto", "Josue", "Carlos"], confirmado: false },
    "espinoza cardoso": { integrantes: ["Ángel", "Paula", "Alison", "Santiago [niño]", "Margarita", "Ricardo"], confirmado: false },
    "mendoza espinoza": { integrantes: ["Arelí", "Samantha", "Johan", "Andrik", "José Fabián Soto Amores"], confirmado: false },
    "jaramillo espinoza": { integrantes: ["Víctor", "Verónica", "Cristian", "Estefania", "Sebastián [niño]"], confirmado: false },
    "salvador beristain": { integrantes: ["Omar", "Alejandra", "Mariana", "Omar h."], confirmado: false },
    "salvador gonzalez": { integrantes: ["Rubén", "Marcos"], confirmado: false },// FALTAN
    "salvador eulogio": { integrantes: ["Jesús", "Carolina", "Jazmín", "Samuel", "Monserrat", "+1 pase"], confirmado: false },
    "corpus carrazco": { integrantes: ["César", "Luz"], confirmado: false },
    "guzman gaspar": { integrantes: ["Giovanni", "Nayeli"], confirmado: false },
    "garcia gallaga": { integrantes: ["Enrique", "Silvia"], confirmado: false },
    "oropeza herrera": { integrantes: ["José Alfredo", "+1 pase"], confirmado: false },
    "perez sanchez": { integrantes: ["Fernando"], confirmado: false },
    "lopez morales": { integrantes: ["Enrique"], confirmado: false },
    "quiroz martinez": { integrantes: ["Misael"], confirmado: false },
    "garcia diaz": { integrantes: ["Elizabeth Ketzalzin", "+1 pase"], confirmado: false },
    "torres benavides": { integrantes: ["Alberto", "Marisela", "Angelica", "+1 pase", "Diego", "+1 pase","+1 pase"], confirmado: false },
    "ledezma luna": { integrantes: ["Liliana"], confirmado: false },
    "velazquez soriano": { integrantes: ["Zelzin"], confirmado: false },
    "venta martinez": { integrantes: ["Mitzi"], confirmado: false },
    "rivera cortes": { integrantes: ["Alexis"], confirmado: false },
    "torres elizarraras": { integrantes: ["Kenia"], confirmado: false },
    "martinez eulogio": { integrantes: ["Fernando", "Teresa", "Sandra", "Aldo [niño]"], confirmado: false },
    "martinez rodriguez": { integrantes: ["Fernando", "Ana Laura", "Iarteh [niño]", "Eithan [niño]"], confirmado: false },
    "hernandez vega": { integrantes: ["Hugo"], confirmado: false }
    // Inivitados novia FIN
};

const nombresVisualesFamilias = {
    // Invitados novio INICIO
    "sanchez espinoza": "Sánchez Espinoza",
    "sanchez espinosa": "Sánchez Espinosa",
    "sanchez aguilera": "Sánchez Aguilera",
    "sanchez miranda": "Sánchez Miranda",
    "sanchez castillo": "Sánchez Castillo",
    "sanchez hernandez": "Sánchez Hernández",
    "sanchez leon": "Sánchez León",
    "sanabria betancourt": "Sanabria Betancourt",
    "rosas galicia": "Rosas Galicia",
    "rosas juarez": "Rosas Juárez",
    "escobar aguilera": "Escobar Aguilera",
    "garcia espinosa": "García Espinosa",
    "piña garcia": "Piña García",
    "garcia alfaro": "García Alfaro",
    "calixto garcia": "Calixto García",
    "sanchez jaramillo": "Sánchez Jaramillo",
    "sanchez rodriguez": "Sánchez Rodríguez",
    "guerrero sanchez": "Guerrero Sánchez",
    "salas sanchez": "Salas Sánchez",
    "baez anastasio": "Báez Anastasio",
    "montiel matilde": "Montiel Matilde",
    "romero velazquez": "Romero Velázquez",
    "mendez olguin": "Méndez Olguín",
    "herrera sanchez": "Herrera Sánchez",
    "curiel gomez": "Curiel Gómez",
    "vazquez cano": "Vázquez Cano",
    "zarate mejia": "Zárate Mejía",
    "silva gonzalez": "Silva González",
    "garcia carreon": "García Carreón",
    "perez nieto": "Pérez Nieto",
    "cabrera bolaños": "Cabrera Bolaños",
    //"espinosa torres": "Espinosa Torres",
    // Invitados novia INICIO
    "espinoza salvador": "Espinoza Salvador",
    "meza salvador": "Meza Salvador",
    "salvador remigio": "Salvador Remigio",
    "salvador lopez": "Salvador López",
    "maldonado salvador": "Maldonado Salvador",
    "espinoza cardoso": "Espinoza Cardoso",
    "mendoza espinoza": "Mendoza Espinoza",
    "jaramillo espinoza": "Jaramillo Espinoza",
    "salvador beristain": "Salvador Beristain",
    "salvador gonzalez": "Salvador González",
    "salvador eulogio": "Salvador Eulogio",
    "corpus carrazco": "Corpus Carrazco",
    "guzman gaspar": "Gúzman Gaspar",
    "garcia gallaga": "García Gallaga",
    "oropeza herrera": "Oropeza Herrera",
    "perez sanchez": "Pérez Sánchez",
    "lopez morales": "López Morales",
    "quiroz martinez": "Quiroz Martínez",
    "garcia diaz": "García Díaz",
    "torres benavides": "Torres Benavides",
    "ledezma luna": "Ledezma Luna",
    "velazquez soriano": "Velázquez Soriano",
    "venta martinez": "Venta Martínez",
    "torres elizarraras": "Torres Elizarraras", 
    "rivera cortes" : "Rivera Cortés",
    "martinez eulogio": "Martínez Eulogio",
    "martinez rodriguez": "Martínez Rodríguez",
    "hernandez vega": "Hernández Vega"
    // Inivitados novia FIN
};